export type IpcChannel =
  // Auth
  | "auth:get-session"
  | "auth:set-session"
  | "auth:clear-session"
  | "auth:open-oauth"
  // Files
  | "files:open-dialog"
  | "files:save-dialog"
  | "files:read-file"
  | "files:write-file"
  // Updates
  | "updates:check"
  | "updates:download"
  | "updates:install"
  | "updates:available"
  | "updates:downloaded"
  | "updates:download-progress"
  // Payments
  | "payments:open-checkout"
  | "payments:open-portal"
  // System
  | "system:get-platform"
  | "system:get-version"
  | "system:minimize"
  | "system:maximize"
  | "system:close"
  | "system:is-maximized"
  | "system:maximized-change"
  | "system:get-theme"
  | "system:set-theme";
